// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw45kyA293kJNVUwtrEhTCcV3J1NzM_JA',
    appId: '1:386153852199:web:386189d5a188d5b3d08d02',
    messagingSenderId: '386153852199',
    projectId: 'fir-notification-test-58f39',
    authDomain: 'fir-notification-test-58f39.firebaseapp.com',
    storageBucket: 'fir-notification-test-58f39.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5lol5RBHbZ2hekVt870JAzLp51Ux_GRU',
    appId: '1:386153852199:android:9885692c8ded1332d08d02',
    messagingSenderId: '386153852199',
    projectId: 'fir-notification-test-58f39',
    storageBucket: 'fir-notification-test-58f39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWwT9I7v83oEbVlEN5AE9A4bf30HcSvbU',
    appId: '1:386153852199:ios:e3ae5a08feb6bf86d08d02',
    messagingSenderId: '386153852199',
    projectId: 'fir-notification-test-58f39',
    storageBucket: 'fir-notification-test-58f39.appspot.com',
    iosBundleId: 'com.example.firebaseNitification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWwT9I7v83oEbVlEN5AE9A4bf30HcSvbU',
    appId: '1:386153852199:ios:2c8dfe7c9e2239bed08d02',
    messagingSenderId: '386153852199',
    projectId: 'fir-notification-test-58f39',
    storageBucket: 'fir-notification-test-58f39.appspot.com',
    iosBundleId: 'com.example.firebaseNitification.RunnerTests',
  );
}
